### ISSUE TITLE
Documentation on how to parse the Morphology

### ISSUE THREAD

**Issue by Ermiaszion** [Freely-Given-org/OpenEnglishTranslation--OET#1]
Hi there,
Would you be able to give some documentation on how to parse the Morphology of both the NT and OT?
For example, what does each letter in the following Morphology represents?
From NT:
Gr,EA,,,,AMS,
From OT:
He,Td:Ncbsa

It would be helpful if you put some explanation on how to parse the Morphology.
Thanks.

**Comment by RobH123** [comment]
Hi @Ermiaszion, you're a bit ahead of me as I'm still focused on drafting the Readers' Version at present which you can start to see displayed at https://Freely-Given.org/OBD from the source files at https://github.com/Freely-Given-org/OpenEnglishTranslation--OET/tree/main/translatedTexts/ReadersVersion.

The NT example you gave seems to be from sourceTexts/BibleTagsOriginals/BibTags.NT.words.tsv I think. That data came from https://github.com/educational-resources-and-services/bibletags-data which came from the unfoldingWord UGNT at https://git.door43.org/unfoldingWord/el-x-koine_ugnt which came from the BHP at https://git.door43.org/unfoldingWord/BHP which uses the morphology codes from section 4.3 of https://www.greekcntr.org/resources/technical.pdf.

The OT example seems to be from sourceTexts/BibleTagsOriginals/BibTags.OT.words.tsv which takes us all the way back to the OSHB project at https://hb.openscriptures.org/parsing/HebrewMorphologyCodes.html.

But you'll find them already explained on my word pages like https://Freely-Given.org/OBD/rf/W/21751.htm#Top (for the NT at least -- I won't be working on the OT this year).

(IIRC, I was looking at the BibleTags files to see if there was already a set of IDs for each Heb/Grk word that I could use, but it turned out that there's already multiple such systems in use so I aborted that.)

**Comment by Ermiaszion** [comment]
Thanks so much @RobH123 for your promote replay. The information you share are helpful, I am working on a project to tag the Hebrew and Greek works to my native language: Tigrinya (Eritrean language). Here is my website: https://www.betezion.com/

Thanks and God bless!
